{% set version = "0.0.11" %}

package:
  name: xarray-topo
  version: {{ version }}

source:
  url: https://gitext.gfz-potsdam.de/sec55-public/xarray-topo/repository/{{ version }}/archive.tar.gz
  sha256: af555e0aa9beecd2bb8c8ec74e8673bb257e001993b89029aec760d2a7bde486

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - xarray >=0.10.0
    - xarray-simlab >=0.2.0
    - numba >=0.35.0

test:
  imports:
    - xtopo
    - xtopo.models
    - xtopo.algos

about:
  home: https://gitext.gfz-potsdam.de/sec55-public/xarray-topo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'xarray extension for for topographic analysis and modeling'

extra:
  recipe-maintainers:
    - benbovy
