appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: T0f57HyRxVYv0CJPmQXyG1MnVpazOvL2YqcF1JPfbauoge7zi3tayJXW58GWclpz/FYFiOLnEH6uVgZxt6lNJoWHHRTUczXry2vU2tTKBCXovQRsTVZOm6ltbWHUgXg3IeiEWi0ef8np84RsE/uZsccm1fZsn6Sx1ALe5ubxC6pQI23SJYF1N8DDgb1hriqhB9MjpoYussMBWK10u4aY4Gl3Covb6MB22MYM0rd0TGL5hgbnOeP8znlvF3pB555pkxHmRSJOrRrRZsMEdQW1hnv1frl4aT7FEIGp8j/cyIpodoEuHx8SkAUXAPQr5tArnflbzdjTU+tpbUFTO8qPCMjx4rXtwHKNOTiX/qrJ5Q6P/AJBlbyw/YyEqaHzlUhoMPByXH7s6Ln679gOe80jwcDMOOpoJDsvmxKNyLyqLIKsGTvQBp8kmNA8f08I+pB5XShs7Me/WzFU5sX/Ux2I+6cJsbahlSHvi8t87Zdc7sCFxImH5D+JIKnWQdlj+h9LBRdTsWmV6D9iEDS7+we0zrzbU1H/xjl5Mjrh2VQT1WkiTikN9K6mIL7xtDDds48v17tVuhsZO9dDad4bqDMZxJs25n2MAeHYCzL7ImqQkHBeOvOAoXT0DGLuydXdNohe5bN3risDwjmTCxWNdNqDjBW0LnpgoVQyIz8m10ezIDc=}
