travis:
  secure:
    BINSTAR_TOKEN: jdY8m6BInmpxNT9eDde2K9CmyYJiBLzE6ODYJbPsbzDH/y/mjA0o3HWSgIpVKvRWZyFF+er4C2AwBVfTq6UVMcW285HFx8DaDXRFeNjX47orex6h7fuoHJPabZc95pVudUv0Z8iSZ1cF6UOkzVuFxSnfGeVSe1iz4cMZfR87VOsne9rAEVjVUjahK8nxD2qiKAyhk38Vze0Lic/nazGJr99kdKnJJR5hxYoJl25W99JabxvbDJwAbm5qI9PcSSm2ImmrcgHFs4CeSJn1zn+E++c93GUp7mOJ3dC+uthuTo6//hVVPR08QE6+JSg9h0dAndvxh/JkdRbvP/gfFrfhXakTUKzjSwtj2i5cE5rXDykKLdll5++bWnJ0DNsvK3C3H/360lCAvBvg+xGAfEwCli+lc5w1VEun5WtviqrRPUmhrjCwHY3WRvQ15YksP9olpcSh8LoAETXtE1WjmMKdFQHKy9mGUAbgzKGQhG99D7H5KpXRrbSmBpgH72JWzOSNICnpA2IBck5IMpSYDyqC3ZkbWlvB3Hv7Hl94A3CPxS6KQ99f7l9mmbpdxvW6KTd6lfZyiRw0N5MR2QYU8eGc7PtcWbwkx6I0iOwM6KjFN/y+5UdfDddM9fklTJAD2Mrk+RlnIgsHrhCyY09RBqw8ESnamz5VUiM0PnyihgIuC0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
